# Generated by Django 5.0.8 on 2024-08-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликована'),
        ),
        migrations.AddField(
            model_name='servers',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя сервера'),
        ),
    ]
