# Generated by Django 5.0.8 on 2024-08-09 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0002_news_is_published_servers_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='servers',
            options={'verbose_name': 'Сервер', 'verbose_name_plural': 'Серверы'},
        ),
        migrations.AlterField(
            model_name='news',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='serv', to='minecraft.servers', verbose_name='Тест'),
        ),
    ]
