# Generated by Django 5.0.8 on 2024-08-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/MinecraftLogo.png', upload_to='media/profiles/%Y/%m/%d', verbose_name='Фото пользователя'),
        ),
    ]
