# Generated by Django 5.0.8 on 2024-08-07 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование доната')),
                ('image', models.ImageField(blank=True, upload_to='media/donates/', verbose_name='Изображение доната')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='donate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='don', to='user.donate', verbose_name='Донат пользователь'),
        ),
    ]
