# Generated by Django 5.0.6 on 2024-08-08 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_donate_profile_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='donate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don', to='user.donate', verbose_name='Донат пользователь'),
        ),
    ]
