# Generated by Django 5.0.6 on 2024-08-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='responsobility',
            field=models.IntegerField(default=2, verbose_name='Сила доната'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donate',
            name='image',
            field=models.ImageField(blank=True, upload_to='donates/', verbose_name='Изображение доната'),
        ),
    ]
