# Generated by Django 5.0.8 on 2024-08-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_donate_responsobility_alter_donate_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donate',
            options={'verbose_name': 'Донат', 'verbose_name_plural': 'Донаты'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
