# Generated by Django 5.0.8 on 2024-08-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_donate_options_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='image',
            field=models.ImageField(blank=True, upload_to='donates/%Y/%m/%d', verbose_name='Изображение доната'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/MinecraftLogo.png', upload_to='profiles/%Y/%m/%d', verbose_name='Фото пользователя'),
        ),
    ]
