# Generated by Django 5.0.6 on 2024-08-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_donate_image_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='donate',
            name='image',
            field=models.ImageField(blank=True, upload_to='donates/', verbose_name='Изображение доната'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/MinecraftLogo.png', upload_to='media/profiles/%Y/%m/%d', verbose_name='Фото пользователя'),
        ),
    ]
